### ISSUE TITLE
01_introduction (cmd 6) StorageException: Server failed to authenticate the request

### ISSUE THREAD

**Issue by JwKateShin** [Azure/LearnAI_Azure_ML#6]
I failed to access the storage that data was stored.
Does anyone please confirm that SAS of Azure Blob storage is still working?

%fs ls /mnt/data/telemetry
[error msg]
shaded.databricks.org.apache.hadoop.fs.azure.AzureException: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

**Comment by wmpauli** [comment]
Thank you @JwKateShin for raising this issue. The SAS had indeed inspired, for security reasons.
